# Generated by Django 4.2.5 on 2023-11-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='anwer',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.CharField(default=''),
        ),
    ]
