# Generated by Django 4.2.5 on 2023-11-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_languagemodel_question_anwer_question_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='anwer',
            new_name='answer',
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(),
        ),
    ]
