# Generated by Django 4.2.5 on 2023-12-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_alter_question_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagemodel',
            name='common_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='languagemodel',
            name='model_name',
            field=models.CharField(max_length=255),
        ),
    ]
