# Generated by Django 4.2.5 on 2023-12-29 15:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_languagemodel_common_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supported_API_Type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='New Conversation Started!', max_length=255),
        ),
        migrations.AlterField(
            model_name='languagemodel',
            name='common_name',
            field=models.CharField(default='hi', max_length=30),
        ),
        migrations.CreateModel(
            name='Model_API',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('common_name', models.CharField(max_length=30, unique=True)),
                ('port', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(65535)], verbose_name='port')),
                ('uri', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.supported_api_type')),
            ],
        ),
    ]
